# Org node types
NODE_TYPE_ENTERPRISE = "ENTERPRISE"
NODE_TYPE_COMPANY = "COMPANY"
NODE_TYPE_DIVISION = "DIVISION"
NODE_TYPE_DEPARTMENT = "DEPARTMENT"
NODE_TYPE_TEAM = "TEAM"
NODE_TYPE_PERSONA = "PERSONA"
NODE_TYPE_CUSTOM = "CUSTOM"

# User types
USER_TYPE_EMPLOYEE = "EMPLOYEE"
USER_TYPE_CONTRACTOR = "CONTRACTOR"

# Project statuses
PROJECT_STATUS_DRAFT = "DRAFT"
PROJECT_STATUS_ACTIVE = "ACTIVE"
PROJECT_STATUS_INACTIVE = "INACTIVE"
PROJECT_STATUS_ARCHIVED = "ARCHIVED"

# Project types
PROJECT_TYPE_EXTERNAL = "EXTERNAL"
PROJECT_TYPE_INTERNAL = "INTERNAL"
PROJECT_TYPE_OVERHEAD = "OVERHEAD"

# Health statuses (RAG)
HEALTH_GREEN = "GREEN"
HEALTH_AMBER = "AMBER"
HEALTH_RED = "RED"

# Task statuses
TASK_STATUS_TODO = "TODO"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_COMPLETE = "COMPLETE"
TASK_STATUS_CANCELLED = "CANCELLED"

# Milestone statuses
MILESTONE_PENDING = "PENDING"
MILESTONE_COMPLETE = "COMPLETE"
MILESTONE_MISSED = "MISSED"

# Project node assignment roles
PNA_ROLE_OWNER = "OWNER"
PNA_ROLE_PARTICIPANT = "PARTICIPANT"
PNA_ROLE_OBSERVER = "OBSERVER"

# Role templates
ROLE_ENTERPRISE_ADMIN = "ENTERPRISE_ADMIN"
ROLE_NODE_ADMIN = "NODE_ADMIN"
ROLE_PM = "PM"
ROLE_MANAGER = "MANAGER"
ROLE_FINANCE = "FINANCE"
ROLE_APPROVER = "APPROVER"
ROLE_EMPLOYEE = "EMPLOYEE"
ROLE_CONTRACTOR = "CONTRACTOR"
ROLE_CUSTOM = "CUSTOM"

# Address owner types
ADDRESS_OWNER_USER = "USER"
ADDRESS_OWNER_WORKPLACE = "WORKPLACE"
ADDRESS_OWNER_NODE = "NODE"

# Geocode statuses
GEOCODE_PENDING = "PENDING"
GEOCODE_SUCCESS = "SUCCESS"
GEOCODE_FAILED = "FAILED"
